### ISSUE TITLE
Battery life with 15.04 and 4.16 Kernel

### ISSUE THREAD

**Issue by growing** [advancingu/XPS13Linux#30]
Hi all,

I bought an XPS last week (non-developer edition, bios AO5) and immediately blasted windows with a total install of 15.04 (kernel 3.19) which worked pretty well out of the box (even the wifi) and got good battery life (> 7 hours at a push). 

I was having problems with an external monitor so upgraded the kernel (as per http://hgdev.co/installing-ubuntu-15-04-on-the-xps-13-9343-2015-a-complete-guide/), which has fixed all the issues, except my battery life is now terrible; sub 3 hours even with screen dimmed, bluetooth off etc. 

Is anyone getting good battery life with this setup? 

Cheers,

Dan

**Comment by patrl** [comment]
Hi there,

Were you using any additional tools for power management under 3.19, such as `TLP`? I'm using 15.04 under 3.19, and my battery life was pretty sub-par until I installed the debian package `laptop-mode-tools` which can be acquired from [here](http://samwel.tk/laptop_mode/packages/debian). This could be worth a try.

-- Patrick

**Comment by growing** [comment]
Hi Patrick,

No power management originally. I've worked out the problem; an app I was running (SQL client) was conflicting with gnome and making gnome-shell run at 100% which was nuking the battery. Closing that app has me back to the original battery life.

Thanks for the laptop-mode-tools suggestion, i'll give that a try.

Cheers!

**Comment by advancingu** [comment]
Looks like this has been resolved.

**Comment by kontrollanten** [comment]
The link posted to `laptop-mode-tools` is now broken. For newcomers checkout https://wiki.archlinux.org/index.php/Laptop_Mode_Tools
