### ISSUE TITLE
Palm detection fix

### ISSUE THREAD

**Issue by hg8** [advancingu/XPS13Linux#32]
Edit : Sorry to have created a new issue. Should have been here : https://github.com/advancingu/XPS13Linux/issues/3

---

Good news?

http://bartongeorge.net/2015/09/30/alternate-touchpad-configuration-for-xps-9343-developer-edition-running-ubuntu-15-04/

**Here my review :**
The Barton George's instructions seem incomplete to me. Here what I have done : 
1.  Install build tools :
   
   ```
   sudo apt-get install git build-essential autoconf automake pkg-config libtool
   sudo apt-get install libmtdev1 libmtdev-dev libudev-dev libevdev-dev xutils-dev
   ```
2. Get `xserver-xorg-dev` : 
   
   ```
    sudo apt-get install xserver-xorg-dev 
   ```
3. Install `libinput` :
   
   ```
    git clone http://anongit.freedesktop.org/git/wayland/libinput
    cd libinput
    ./autogen.sh --prefix=/usr
    make && sudo make install
   ```
   
    _Note : I don't know why but `git clone http://cgit.freedesktop.org/wayland/libinput/` is not working for me._
4. Install `xf86-input-libinput` : 
   
   ```
     git clone http://cgit.freedesktop.org/xorg/driver/xf86-input-libinput/
     cd ../xf86-input-libinput
     ./autogen.sh --prefix=/usr
     make && sudo make install
   ```
5. Log out and re-open your session.
6. Add touchpalm detection : 
   
   ```
     sudo nano /usr/share/X11/xorg.conf.d/99-libinput.conf
   ```
   
   And paste this before `EndSection` : 
   
   ```
   Option "Tapping" "True"
   Option "PalmDetection" "True"
   ```

Can someone please test it and tell me theirs results ? I am having trouble to test if this is working properly... Thanks in advance.

**Comment by jared-dominguez** [comment]
Barton's going to update the instructions our support person put together for him. He accidentally left part of it out.

**Comment by advancingu** [comment]
Closing since this will be updated on the Sputnik blog.
