### ISSUE TITLE
Touchpad Select Issue

### ISSUE THREAD

**Issue by cerealcable** [advancingu/XPS13Linux#33]
From time to time my touchpad gets stuck in the selection mode and ultimately is very frustrating as you are always scrolling, selecting text or worse dragging text, tabs, etc. I have the QHD+ touch display and I think it could be related to the touch display as well as the trackpad both receiving inputs?

I had this issue with the stock install of the laptop, but have since installed Ubuntu 15.04 in hopes to rectify the issue. I've also tried blacklisting psmouse which did not change my experience. Sadly its not consistent and easily replicated unless I just start writing code on the laptop in which case something always seems to trigger it.

Anyone else with this issue?

Details:
- Ubuntu 15.04
- QHD+ Display
- A05 BIOS

**Comment by marcbelmont** [comment]
I have the same issue (touchpad is stuck in selection mode). Going to the mouse preferences in the control center and disabling / enabling the touchpad sometimes help.

This problem usually occurs when I do lots of **drag and drops**. Just clicking and scrolling (with 2 fingers) have not triggered the problem.

```
Linux marc 4.1.6-040106-generic #201508170230 SMP Mon Aug 17 06:32:14 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
Ubuntu 15.04
```

### Update

When the touchpad is stuck, the **top left corner** still works.  Clicking in the top left corner, fixes the touchpad.

**Comment by cerealcable** [comment]
Yeah I have the settings pinned so that I can quickly and easily toggle the touchpad. I haven't seen an instance where it doesn't work yet, though its quite irritating when it happens.

**Comment by ChrisJMiles** [comment]
Yes, exactly the same problem for me. I'm running 15.04 on a QHD+ display with A05 bios. I feel that this issue got significantly worse after some Ubuntu system updates a week or so ago, but it has always been around since I got the unit. I solve it generally by using a wireless mouse! Not exactly optimal, though! I checked the temporary fix you both are talking about above (resetting the touchpad in settings) and it has worked to stamp it out -- I will now wait to see exactly what behaviour brings it back after the touchpad reset (a re-boot, an update, the passing of time?!).

**Comment by cerealcable** [comment]
Yeah, I think that's the part that makes it hard to report. Not sure what produces this and thus I can't realistically reproduce it on demand which would be great. I'm glad I'm not the only one!

**Comment by achiang** [comment]
I've been seeing this too, on the standard Ubuntu 14.04 factory installation, QHD+ display, and A05 bios.

It's been happening for over a month now. I've been kinda trying to debug it but nothing interesting has appeared in `/var/log/syslog` nor in `$HOME/.xsession-errors`.

**Comment by pdelanauze** [comment]
@cerealcable Can you confirm that you actually have the a06 bios ? and that its not a typo ?

**Comment by cerealcable** [comment]
@pdelanauze Was a typo, I fixed that. Sorry!

**Comment by pdelanauze** [comment]
Actually , i've experienced this issue in gnome when under kernel 3.9.x .. Just moved to a 4.1 kernel , and havent come across this issue since.

```
Linux pat-xps 4.1.0-040100-generic #201507030940 SMP Fri Jul 3 09:41:47 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by cerealcable** [comment]
I'm running 4.2 and from time to time experience the issue.

```
Linux xps13 4.2.0-16-generic #19-Ubuntu SMP Thu Oct 8 15:35:06 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by dchambers** [comment]
I've been having this issue since I got my laptop, but I don't think I first saw it till after I configured my trackpad to make it more usable. The tip from @marcbelmont works for me, except that for me it's the top-right corner that I have to click. Oh, I'm running Linux 4.1.6 with an A05 bios.

**Comment by cerealcable** [comment]
It's been years since I've hard this hardware, so going to close this issue.
