### ISSUE TITLE
Keyboard back-light on at boot and resume

### ISSUE THREAD

**Issue by rosolko** [advancingu/XPS13Linux#37]
Related to [this](https://askubuntu.com/questions/689907/dell-xps-13-9343-keyboard-backlight-on-at-boot-ubuntu-15-10) post and [solution](https://askubuntu.com/questions/689907/dell-xps-13-9343-keyboard-backlight-on-at-boot-ubuntu-15-10/711291#711291) 

Workaround:
1: Save script to 

```
/usr/local/bin/xps13-kbd-backlight
```

Make it as executable 

```
sudo chmod +x <script>
```

2: Problem part
3: Link to /etc/pm/sleep.d

```
ln -s  /usr/bin/xps13-kbd-backlight /etc/pm/sleep.d/20_xps13-kbd-backlight
```

A problem:
Partially this solution is working - if talking about back-light on resume, but on boot - I have no luck.

The problem is in this part of the solution:

```
using preferences set in ${BL_CONF}
[/etc/xps13-kbd-backlight]
```

How can I set this value?

**Comment by r2rien** [comment]
I answered you in
https://github.com/mpalourdio/xps13/issues/75
